### ISSUE TITLE
Request: Migrate to KiCAD v8

### ISSUE THREAD

**Issue by DeflateAwning** [ebastler/UnMechanical#2]
Seems like the preview of the migration to KiCAD v8 missed some layers.

Would love to see it in the latest version to continue its development! 

Specifically, it looks like the `User.Drawings` layer is offset. It's possible it was that way in a previous rev too though.

**Comment by ebastler** [comment]
Thank you - the user.drawings layer was where I imported my CAD drawings, then apparently I did not rotate it along with the rest of the PCB when rearranging for panelization. I removed the contents of that layer altogether, as they are not necessary anymore and were just positioning aids to create the outline and switch positions.

Also, updated the footprints from library so 3D model paths are correct again (whyever they change between versions).
